### PR TITLE
Fix giscus blog post

### PR DESCRIPTION
**Pull request by eerison**
- Fixed giscus blog post
- Change the docker-compose.yaml to latest node version (20)

### CODE REVIEW

**Comment by eerison** [comment]
Hello @FjellOverflow 

thank you for this amazing integration, Could you take a look in this PR please

unfortunately  I couldn't make this work without pass a value on `client:value="react"`

more info: https://docs.astro.build/en/reference/errors/no-client-only-hint/

**Comment by FjellOverflow** [comment]
Thanks @eerison!
Yeah, your changes and docs reference checks out, I guess I overlooked it :smile: , good job!
For anyone wondering why it might've still worked without (myself included), on `build`, Astro gives the helpful warning
```bash
The client:only directive for Comments is not recognized.
The renderer @astrojs/react will be used. If you intended to use a different renderer, please provide a valid client:only directive.
```
Guess I also overlooked that :smile:

**Comment by eerison** [comment]
then I guess we could merge it @satnaing 

:)

**Comment by satnaing** [comment]
LGTM too.
Thanks for your contribution 🎉

**Pull request merged**
