### PR TITLE
Eliminating postSlug property and general slugify rework

### PR DESCRIPTION
**Pull request by Because789**
This is a proposal to solve https://github.com/satnaing/astro-paper/issues/186. After digging through the AstroPaper code base for hours, I strongly believe, that these changes will make the base of the template more robust for future developments. Especially the _postSlug_ property opens the door for some nasty issues, getting rid of it is in my opinion a necessity. This also means, that [Front Matter CMS](https://github.com/estruyf/vscode-front-matter) is compatible with this version of AstroPaper.

There are a lot of files, which had to be changed. But it looks much more intimidating, than it is, because in most of the cases there are only tiny changes. I added a [change log](https://github.com/Because789/astro-paper/blob/slugify-rework/CHANGELOG-Because789.md), there you can find an overview, on what is done. 

I've tested this version carefully, and I feel pretty good about it, but obviously it needs to get thoroughly reviewed.

@satnaing I would appreciate, if you could give me a hint, whether you are interested in merging this, or not. For me, it's fine either way, I just would like to know if I should focus on my own fork or continue contributing to what in my opinion is the best Astro blog template out there :smile:

### CODE REVIEW

**Comment by vrabe** [comment]
The PR adds too many changes. Some are unrelated, like introducing pnpm, dev container, and Front Matter CMS. It's better to focus on removing postSlug property.

**Comment by Because789** [comment]
I completely understand, this is my first bigger PR and I kind of knew I messed it up while doing it. The important changes are: 

[Replaced "postSlug" occurrences with "slug" where needed.](https://github.com/satnaing/astro-paper/pull/194/commits/f4e709e68563fa8d3bc6e84835717fe46f82cb18)
[Eliminated use of slugify() by simply using the Astro slug property.](https://github.com/satnaing/astro-paper/pull/194/commits/428ac4f36b838b25a7f70000f2266e882bb58633)
[Eliminated use of slugifyStr() and slugifyAll() by replacing it with …](https://github.com/satnaing/astro-paper/pull/194/commits/574acd8d79280c68bbf072966010dcdc0b2586a7) 
[Updated dependencies, deleted slugify.ts and added change log.](https://github.com/satnaing/astro-paper/pull/194/commits/e00e49c49be62ad43a81e4c4090191b246b02246)

The first two commits focus on the slug property, the last two on the rest of the slugify.ts function. I could clean up the PR or make a new one, but I only gonna put more work into it if I @satnaing agrees with the general direction. If he thinks these changes are unnecessary, there is no point anyway.

**Comment by satnaing** [comment]
Hello @Because789 
Thanks for your interest in contribution to this project.

Replacing `postSlug` with Astro's `slug` is indeed a great direction. However, I need to make sure that everything works fine by doing so. Since `postSlug` and `slugify` are use a lot in AstroPaper, it will definitely be breaking changes and I have to check every single edge cases (for example, OG Image generation, multi-lang issues etc).

On the other hand, I've been trying to upgrade for the Astro v4. (So, AstroPaper will be v4 too with some breaking changes).

While the effort and intention of this PR for new features are really great, I cannot accept your PR this time.

**Comment by Because789** [comment]
Hey @satnaing, nice to hear from you. I understand, in the meantime my focus shifted anyway, and I started my own template. So I'm happy I don't have to deal with this anymore 😄 Wish you all the best!

**Pull request closed without merging**
