### PR TITLE
Refactor: Single source of truth for site URL

### PR DESCRIPTION
**Pull request by tanishqmanuja**
Note:

```ts
import { SITE } from "./src/config"; // ✔️ will work

import { SITE } from "@/config" // ❌ will not work (outside src dir) bc of tsconfig baseUrl;
```

related: #142

### CODE REVIEW

**Comment by satnaing** [comment]
Which problem can occur when we use or don't use `.mjs`? What could possibly wrong?
Currently, I see a type error in `remarkToc` when we use `.ts`. 
However, when I change back to `.mjs`, that error just gone.

**Comment by tanishqmanuja** [comment]
Since the config file has a .ts extension in not semantically incorrect to import a uncompiled .ts file into .mjs file

**Comment by mattppal** [comment]
This works for me too— thanks for the update @tanishqmanuja

**Comment by satnaing** [comment]
In order to resolve the type error, I had to update the dependencies to the latest one.

**Review by satnaing — APPROVED** [review]
Just make some minor updates on my own.

**Comment by tanishqmanuja** [comment]
@satnaing, can you add hacktoberfest tag to the repo till nov 1, would be great 😸

**Comment by satnaing** [comment]
@tanishqmanuja 
Yep, I wanted to participate in Hacktoberfest as a maintainer. However, I'm a bit hesitant in case there are a lot of pull requests that I have to review. 
Besides, at the moment, this repo doesn't have issue templates, review templates, etc.

On the other hand, I'm also thinking of participating in Hacktoberfest.

**Comment by tanishqmanuja** [comment]
I personally think there wouldn't be lots of requests. Plus there is no negative outcome in the case there are, We could solve them one by one as usual :)

**Pull request merged**
