### PR TITLE
feat: add prev/next links at the bottom of blog post

### LINKED ISSUE #358: Feature request: Add previous and next posts
After reading a blog post, readers might leave the site immediately. To address this, consider adding recommendations for other posts, such as previous and next posts by date, or related posts at the bottom of a blog post. By providing these recommendations, the blog can encourage readers to stay longer, explore additional content, and potentially increase engagement and retention.

Post recommendations

### PR DESCRIPTION
**Pull request by satnaing**
Add `Prev Post` and `Next Post` links at the bottom of a blog post.

### Desktop 
image

### Mobile
image

Resolves #358

### CODE REVIEW

**Review by barnett617 — COMMENTED** [review]
LGTM

**Comment by barnett617** [comment]
> LGTM

I find something maybe @satnaing you should take into consideration which is once a post page can navigate to sibling post pages, the "Go back" button behavior may be redesigned.
Because if you change to a new page by using prev/next link, the "Go back" will take you to the last post page rather than back to Posts page.
This may seems wired because you can be more hard to back to Posts page until you back to the first post page you clicked from Posts.

**Comment by satnaing** [comment]
Good point! @barnett617 
I'll look into it after #376 since merging this PR will affect that PR.

**Comment by satnaing** [comment]
> I find something maybe @satnaing you should take into consideration which is once a post page can navigate to sibling post pages, the "Go back" button behavior may be redesigned.
Because if you change to a new page by using prev/next link, the "Go back" will take you to the last post page rather than back to Posts page.
This may seems wired because you can be more hard to back to Posts page until you back to the first post page you clicked from Posts.

At the moment, I'll just leave the "Go back" behavior as it is.
Unlike other buttons (or links), "Go back" button behavior is a bit complicated since a blog post can be navigated from "Posts page", "Home page", "Tag page" and "Search page".
So, it's not very ideal to Go back to the "Posts page" whenever "Go back" button is clicked. Plus, users can go to "Posts page" by clicking the "Posts" in the nav bar too.
Current implementation is to "Go back" to the previous page using browser's history API.
Probably a breadcrumb is a good fit in this case. I'm not sure tho.

**Pull request merged**
