### PR TITLE
Sessionize Social Icon

### PR DESCRIPTION
**Pull request by aatmmr**
This pull request adds support for the "Sessionize" social media platform in the application. It includes changes to the `socialIcons.ts` file to add a new social icon for "Sessionize", updates the `SocialMedia` type in `types.ts` to recognize "Sessionize" as a valid platform, and adds support for "Sessionize" as a social media platform in the application's configuration.

Main changes:

* <a href="diffhunk://#diff-fe79ed0b7ffb6dbec39a5a08664209b1b88c4da81ff463808fad733aa85e5f60R211-R216">`src/assets/socialIcons.ts`</a>: Added a new social icon for "Sessionize" in the `socialIcons.ts` file.
* <a href="diffhunk://#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aL42-R43">`src/types.ts`</a>: Updated the `SocialMedia` type to recognize "Sessionize" as a valid social media platform.
* <a href="diffhunk://#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012R143-R148">`src/config.ts`</a>: Added support for "Sessionize" as a social media platform in the application's configuration.

### CODE REVIEW

**Comment by aatmmr** [comment]
@satnaing thank you very much for that awesome theme! I'd like to contribute a social icon that I was missing from the list. 

Is there any PR/review workflow you intend to use. It appears that I could simply merge the changes into the main branch. Furthermore, I enable Advanced Security (GHAS) on my repo and it immediately opened 4 PR's for security updates. I highly recommend using GHAS as it comes for free for public repos. I am happy to assist you in setting it up.

**Comment by satnaing** [comment]
Hello @aatmmr 
Thank you for your suggestion and PR. I truly appreciate your effort.

After some thought, I've decided to keep the project supporting only a specific set of popular social icons. If users wish to include a new social media platform, they can integrate it on their own. The current set of social icons should be sufficient for most users.

I hope this decision doesn't disappoint you. If you have any other ideas or changes you'd like to propose in the future, please feel free to share them.

Thanks again for your understanding.
Look forward to your continued involvement in the project.

**Comment by satnaing** [comment]
urthermore, I enable Advanced Security (GHAS) on my repo and it immediately opened 4 PR's for security updates. I highly recommend using GHAS as it comes for free for public repos. I am happy to assist you in setting it up.

> Is there any PR/review workflow you intend to use.

Yes, I'm thinking of integrating a CONTRIBUTION guide line and issue template in the future.

> It appears that I could simply merge the changes into the main branch. 

Does it? I didn't notice anything strange. Is there any procedure I should follow?

> I highly recommend using GHAS as it comes for free for public repos. I am happy to assist you in setting it up.

I believe I've already enabled GHAS in AstroPaper.

**Comment by satnaing** [comment]
> No worries @satnaing - if someone is looking for the icon the PR is still around and searchable, hence a tutorial to add a new icon. A post in the template could be useful to show how this is done 🤔

Yep
Good idea. Maybe a blog post under `#faq` tag.
You can make a PR for that if you wish.

**Comment by aatmmr** [comment]
> I believe I've already enabled GHAS in AstroPaper.

Yes, you did - there are PRs for dependency updates - I unfortunately missed that when writing as I just had the instant dependabot updates in my repo in mind 😅

**Pull request closed without merging**
