### PR TITLE
fix: resolve issue with non-Latin characters not displaying correctly on OG images using Google Fonts API

### PR DESCRIPTION
**Pull request by cantpr09ram**
hello-你好-안녕-こんにちは-χαίρετε-hallå

| before | after |
| :----: | :---:| 
| before_jp | after_jp |
| before_cn | after_cn |

if you want more language support you can add it on your own
```js
const fontsConfig = [
   { name: "Noto Sans JP", font: "Noto+Sans+JP", weight: 400, style: "normal", },
   { name: "Noto Sans JP", font: "Noto+Sans+JP:wght@700", weight: 700, style: "normal", }, 
   { name: "Noto Sans", font: "Noto+Sans", weight: 400, style: "normal" },
   { name: "Noto Sans", font: "Noto+Sans:wght@700", weight: 700, style: "normal", },
  ];
```

### CODE REVIEW

**Comment by satnaing** [comment]
Thanks for your PR @cantpr09ram.
I need to check this in detail along with dependency (Satori) upgrade.
BRB.

**Comment by satnaing** [comment]
Hello @cantpr09ram 
Are you able to build the project?
I've got `First argument to DataView constructor must be an ArrayBuffer` error when I tried building the project.

**Comment by satnaing** [comment]
Hello @cantpr09ram 
I co-authored some changes
- resolved conflicts with the main branch and rebased
- fixed font loading issue in og.png.ts via site.tsx
- added a new section in blog post

Thanks for your contribution.

**Comment by cantpr09ram** [comment]
hi @satnaing 

Sorry for the delay in getting back to you. I've been swamped with final exams. Thanks a ton for your project and for merging my changes. It’s much appreciated!

**Pull request merged**
