### PR TITLE
Sorted the rss feed from latest to oldest.

### PR DESCRIPTION
**Pull request by saif71**
Sorted the rss feed from latest to oldest. Which is crucial for RSS readers.

### CODE REVIEW

**Review by satnaing — CHANGES_REQUESTED** [review]
Thanks for pointing this out.
Appreciate your work. But, AstroPaper already has a util function called `getSortedPosts` for sorting blog posts. This util func automatically filters out the draft posts and sort according to `pubDatetime`. 

It'd be solved you change something like this
```js
  const posts = await getCollection("blog");
  const sortedPosts = getSortedPosts(posts);
  return rss({
    //  ---
    items: sortedPosts.map(({ data }) => ({
    // ---
      })),
  });
}

**Comment by saif71** [comment]
ah right. I forgot about the util func.. @satnaing

**Review by saif71 — COMMENTED** [review]
ya i think this works

**Comment by satnaing** [comment]
So, would you like to update the requested changes? 
Or would you like to close the PR? @saif71

**Comment by saif71** [comment]
@satnaing No no. I don't want to close. I will update the request. I'm just not getting enough time this week to do so.. Sorry :(

**Comment by satnaing** [comment]
Ok Ok, got it!

**Comment by saif71** [comment]
@satnaing really sorry for the delay. I've pushed another commit. This time using the util func as you requested. Hope you will be able to merge it now.. Thanks.

**Comment by satnaing** [comment]
I made tiny updates in PR. But overall, LGTM now.
Thanks!

**Pull request merged**
