### PR TITLE
OG Image Reworks

### PR DESCRIPTION
**Pull request by tanishqmanuja**
PR for reworking OG image generation and routing logic

### CODE REVIEW

**Comment by tanishqmanuja** [comment]
Also made SITE.ogImage optional, if not provided a fallback (generated) image we be used instead.
og

**Comment by tanishqmanuja** [comment]
@satnaing, can you test the OG generation on your setup. Just to be extra sure :)

**Comment by satnaing** [comment]
Love it. Much simpler now.
Do you think there are any edge cases we might have missed?

I've checked special character issues and it all works well.

**Comment by tanishqmanuja** [comment]
It's difficult for a dev to find their own bugs 😅, So no edge cases that i can think of for now. I have tested the following cases:
- No ogImage tag provided in frontmatter of blog will create and use png from the endpoint
- ogImage works both when providing relative path like ./_images/foobar.png using astro image sourcing and absolute path in public folder /assets/foobar.png
- Using an external url like https://xyz.com/foobar.png (haven't tested this case on a deployed site but it should work just like before ig)

**Comment by satnaing** [comment]
@tanishqmanuja 
I tested the following

- [x] special characters in title
- [x] relative path 
- [x] alias path 
- [x] absolute path
- [x] external images

**_Relative Path_**
```md
# image is `src/assets/example.png`
ogImage: "../../assets/example.png"
```

**_Alias Path_**
```md
# image is `src/assets/example.png`
ogImage: "@assets/example.png" 
```

**_Absolute Path_**
```md
# image is `public/example.png`
ogImage: /example.png
```

Everything seems to be okay.
I'm gonna merge your PR now. Thanks for your contribution. ✌🏻

**Comment by satnaing** [comment]
BTW @tanishqmanuja 
Since you're familiar with these changes, would you be interested in collaborating on documenting the upgrade guide? However, it's okay if you have a busy schedule.

I'm planning to create a PR for the documentation tomorrow or on Saturday.

**Comment by satnaing** [comment]
Yep, agree with you. Mostly `Case 3` would be the easiest approach.
However, there will be many users who can't do the second and third options (case 2/3).

For `Case 1,` I can't think of any approach other than using Git. I've also written [an article](https://astro-paper.pages.dev/posts/how-to-update-dependencies/#updating-astropaper-using-git) about that. 

If they don't want to do that, they can store/backup their changes and customizations. Those files and directories would probably be `src/content/blog/`, `src/config.ts`, `src/pages/about.md`, `public/` and maybe `src/styles/base.css`. Then, replace anything else with the newer version of AstroPaper.

I think these are the only ideal ways to upgrade AstroPaper. 
This v3 upgrade might be a little bit painful since I couldn't keep up to date with Astro versions regularly.
Gotta try harder for frequent minor updates in the future.

**Pull request merged**
