### PR TITLE
Dockerfile added to build static files and serve with NGINX image

### PR DESCRIPTION
**Pull request by michealch**
This PR includes a Dockerfile and .dockerignore that uses a two-stage build process: building static files with Node.js and serving them via a official NGINX image. The initial build stage uses node:lts to install dependencies and compile the application into static files. Second stage serve the static files with unprivileged NGINX Image. 

Key Changes:
1. Implemented multi-stage build to separate build and runtime environments.
2. NGINX image for the runtime stage.

Build the Image by executing
`docker build -t <image_name>:<image_tag> .`

Run the Container by executing
`docker run -p 8081:80 <image_name>:<image_tag>`

The webpage should be accessible at http://localhost:8081

### CODE REVIEW

**Comment by michealch** [comment]
@satnaing yes, the issue is that the base image is not compatible with the ARM processor. I will create a base image that is compatible with ARM and push it. As soon as I have done so, I will let you know.

**Comment by michealch** [comment]
@satnaing fixed the issue by replacing the distroless image to official nginx unprivileged image. it should work fine now :)

**Comment by michealch** [comment]
i have updated runtime image to official nginx image. Please merge the PR.

**Comment by satnaing** [comment]
Thanks for your contribution.
Can you also add some instructions in README in order to run this Dockerfile?

**Review by satnaing — APPROVED** [review]

**Comment by eerison** [comment]
Hey @michealch 

have you tried to use the [docker-compose.yaml](https://github.com/satnaing/astro-paper/blob/main/docker-compose.yml)?
it will make you run astro paper on docker, you don't need to create a Dockerfile for this, or am I missing something here?

**Comment by michealch** [comment]
Hey @eerison 
The docker-compose.yaml you have mentioned is for dev purpose and not for production. Dockerfile is there to build container image with static files for production purpose.

**Pull request merged**
