### PR TITLE
feat: astro-3.0 and all dependencies updated

### PR DESCRIPTION
**Pull request by Luks17**
closes https://github.com/satnaing/astro-paper/issues/111

Description: This PR aims to be a simple port of astro-paper to Astro 3.0, no new features introduced in that update were added. A lot of styles were broken in the update, so this PR also fixes them.

### CODE REVIEW

**Comment by timrwwatson** [comment]
Apologies if dumb question: is there a way to sort out the deprecation warnings I assume your getting in [ogTitle].svg.ts for returning a simple object etc ?

**Comment by Luks17** [comment]
> Apologies if dumb question: is there a way to sort out the deprecation warnings I assume your getting in [ogTitle].svg.ts for returning a simple object etc ?

I purposefully avoided fixing that because I did not find it on the [changelog](https://github.com/withastro/astro/releases/tag/astro%403.0.0) and didn't want to break it. However, I just found it documented at the very end of the page, so will try to fix it later.

**Comment by Luks17** [comment]
> Apologies if dumb question: is there a way to sort out the deprecation warnings I assume your getting in [ogTitle].svg.ts for returning a simple object etc ?

Should be solved now

**Comment by timrwwatson** [comment]
> > Apologies if dumb question: is there a way to sort out the deprecation warnings I assume your getting in [ogTitle].svg.ts for returning a simple object etc ?
> 
> Should be solved now

Works for me, I think there might have been another warning in rss.xml.ts, but i've modified/forked my original and since then done other things. So I think that one might need something too?

`return new Response(JSON.stringify(rss({
    title: SITE.title,
    description: SITE.desc,
    site: SITE.website,
    items: sortedPosts.map(({ data }) => ({
      link: `posts/${slugify(data)}`,
      title: data.title,
      description: data.description,
      pubDate: new Date(data.pubDatetime),
    })),
  })));`

such as ^^

**Comment by satnaing** [comment]
I truly appreciate your PR and your dedication to this. Thank you for your hard work.

I've also been working on the same issue locally, and I noticed that many of the changes in your PR are similar or identical to what I've been working on. If there are any changes, features, or bug fixes that you've made, which are not present in my PR, would you be open to merging them into my PR?

**Comment by Luks17** [comment]
> I truly appreciate your PR and your dedication to this. Thank you for your hard work.
> 
> I've also been working on the same issue locally, and I noticed that many of the changes in your PR are similar or identical to what I've been working on. If there are any changes, features, or bug fixes that you've made, which are not present in my PR, would you be open to merging them into my PR?

I will check it out!

**Comment by alec-c4** [comment]
Guys, may I ask you to add RTFM how to update existing blog with this release?

**Comment by satnaing** [comment]
@alec-c4 
That will also be added soon. In the meantime, if you'd like, you can start experimenting with the new version on your own by examining the commit history, such as [this PR](https://github.com/satnaing/astro-paper/pull/112/commits) or [mine](https://github.com/satnaing/astro-paper/pull/114/commits).

**Comment by satnaing** [comment]
@alec-c4 
That will also be added soon. In the meantime, if you'd like, you can start experimenting with the new version on your own by examining the commit history, such as [this PR](https://github.com/satnaing/astro-paper/pull/112/commits) or [mine](https://github.com/satnaing/astro-paper/pull/114/commits).

**Comment by satnaing** [comment]
@alec-c4 
That will also be added soon. In the meantime, if you'd like, you can start experimenting with the new version on your own by examining the commit history, such as [this PR](https://github.com/satnaing/astro-paper/pull/112/commits) or [mine](https://github.com/satnaing/astro-paper/pull/114/commits).

**Pull request closed without merging**
