### PR TITLE
feat: implement back-to-top button in blog post page

### PR DESCRIPTION
**Pull request by satnaing**
Implement back-to-top button under tags in PostDetails page. Update html scroll-behavior to smooth.

Closes: #156

### CODE REVIEW

**Comment by Because789** [comment]
That looks great, makes much more sense like that!

While clicking around, I noticed something I haven't noticed before: In MS Edge, the title view transitions from post list to details and back are sometimes a bit wonky (it stretches over the whole box for like a ms and then snaps back). It's most visible with short titles, like the "AstroPaper 3.0" post. I thought it might have to do with the "html: smooth" change, but turns out that it was there before. It seems very situational, can't notice it in Firefox, and even in Edge it's not visible 100% of the time. One of those ugly problems, but it feels like that should be an issue of Astro itself.

**Comment by satnaing** [comment]
Yep.
Maybe because of view transitions api. Not sure the exact reason tho. 
Hopefully will be solved eventually by upgrading Astro.

**Comment by diomed** [comment]
very bad.

I was hoping for nice floating _back to top_ button such as here in this example: 
https://www.ub.cafe/posts/post-title-29

**Comment by Because789** [comment]
> very bad.
> 
> I was hoping for nice floating _back to top_ button such as here in this example: https://www.ub.cafe/posts/post-title-29

Dude, could you at least show some respect, when other people do work FOR FREE for you? If you don't like the implementation, make a better one for yourself. Good luck.

**Comment by diomed** [comment]
nowadays back to top buttons are more advanced, like that one in my example. 

that basically isnt really a button but a link , that I could have made. 

I expected a bit more complexity - like fade in/ fade out on scroll.

**Comment by Because789** [comment]
Then go and learn how to do it yourself. And if you are too lazy for that, at least learn how to ask nicely. Nobody here ows you anything, but If you show some human decency, amazing things can happen. 

Anyway, you've got a lot to learn. Good luck.

**Pull request merged**
