### PR TITLE
feat: add edit post feature

### PR DESCRIPTION
**Pull request by barnett617**
This PR implements the feature "edit page" by referring to the implementation of [Hugo PaperMod](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/edit_post.html)

close: #191

### CODE REVIEW

**Comment by satnaing** [comment]
Thanks for your PRs @barnett617 
I'll look into them later since they have to be reviewed carefully.

**Comment by satnaing** [comment]
I think it will make more sense to display "Suggest Changes" inside post detail page.
What do you think? @barnett617 
For that, we can do something like this since `Datetime` in post detail page will always be `lg`.

```tsx
{size === "lg" && <EditPost editPost={editPost} postId={postId} />}
```

**Comment by barnett617** [comment]
> I think it will make more sense to display "Suggest Changes" inside post detail page. What do you think? @barnett617 For that, we can do something like this since `Datetime` in post detail page will always be `lg`.
> 
> ```tsx
> {size === "lg" && <EditPost editPost={editPost} postId={postId} />}
> ```

It's up to you because it's relative to this blog theme layout style, i just implement this refers to [Hugo PaperMod](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/edit_post.html).
So it's okay to adjust it's display layout driven by your design.

**Review by No1ceTea — APPROVED** [review]

**Review by satnaing — APPROVED** [review]

**Comment by satnaing** [comment]
I just updated what I mentioned, and updated the docs post.
Thanks for the PR.

**Pull request merged**
