### PR TITLE
Add view transitions for card on search page

### PR DESCRIPTION
**Pull request by tanishqmanuja**

### CODE REVIEW

**Comment by satnaing** [comment]
@tanishqmanuja 
Thanks for this PR.

Just one thing. I created `Card.astro` only because I didn't realize we could add ViewTransitions in `jsx`.
If we can achieve that in `Card.tsx`, I assume we don't need a separate `Card.astro` file anymore.

Additionally, we can also put related styles back inside `Card.tsx`. 
What do you think?

**Comment by tanishqmanuja** [comment]
Sounds good to me.

**Comment by satnaing** [comment]
So, do you want to make changes on your own? Or do you want me to co-author the changes?

**Comment by tanishqmanuja** [comment]
I would be happy with both of the options. I have to do that for my fork anyways, so I will push here, if it needs any refinement you can co-author :)

**Comment by satnaing** [comment]
So far so good. I just made a small change.
Thanks for your contribution.

**Pull request merged**
