### PR TITLE
feat: Add docker-compose file

### LINKED ISSUE #172: Create a default docker compose configuration
I guess we could add a default docker-compose config file to make astro paper work without install dependencies locally.

### PR DESCRIPTION
**Pull request by eerison**
- Add `docker-compose.yml` file
- Add docker commands into the README.md file

Close #172

### CODE REVIEW

**Comment by satnaing** [comment]
I can't run the app without running `docker compose run app npm install`. Then `node_modules` will appear in my local machine. 
Can you tell me some steps to run docker-compose file?

Docker is not my area of expertise, and thus you can tell me if I'm wrong.
Here are my steps
1) install dependencies with `docker compose run app npm i`
2) run docker-compose with `docker compose up -d`

**Comment by eerison** [comment]
Hey @satnaing 

just to make sure do you have docker locally?

just to make sure run

```sh
docker compose version  
# Docker Compose version v2.23.0-desktop.1
```

if you could see the version then you should run the steps that you said above

> install dependencies with `docker compose run app npm i`
> run docker-compose with `docker compose up -d`

if it is not working what error appear for you?

**Comment by satnaing** [comment]
@eerison 
Yep, I went through those steps.
One thing I'm confused is that `node_modules` still need to be in my local environment.

So, here's what I do.
1) delete `node_modules` from my local
2) docker compose run app npm i
3) docker compose up -d

When I did step 2, `node_modules` appeared in my local.
Is it what is supposed to be? Juz curious!

**Comment by eerison** [comment]
> Is it what is supposed to be? Juz curious!

Yep it is expected, because when something is updated into de container,  it is binding to your machine,  and also the other way around,  if you updated something,  it will appear into the container. 

But the question is , didn't it work?


If not there are few things we could check 


docker compose logs 
docker compose ps (here you should see the container up, If it isn't up, maybe you have something running on port 4321)

**Comment by satnaing** [comment]
Oh okay.
Everything works fine. 
I just wanted to know this 👇🏻

> When I did step 2, node_modules appeared in my local.
Is it what is supposed to be? 

I'll make small adjustments in `README` and merge this PR.
Thanks for your contribution.

**Pull request merged**
