### PR TITLE
Remove [page].astro

### PR DESCRIPTION
**Pull request by floatingpurr**
tl;dr, Delete src/pages/posts/[page].astro

Hi folks, just a quick update about pagination. I noticed that there were two identical files: [page].astro and [...page].astro. As per the [Astro doc](https://docs.astro.build/en/reference/api-reference/#paginate), we only need one of them:

- /posts/[page].astro would generate the URLs /posts/1, /posts/2, /posts/3, etc.
- /posts/[...page].astro would generate the URLs /posts, /posts/2, /posts/3, etc.

I've removed src/pages/posts/[page].astro to avoid duplication and to maintain consistency with the "legacy" URL pattern.

### CODE REVIEW

**Comment by satnaing** [comment]
Thanks for your PR.
This approach has one issue.
We can't access `/posts/1` anymore.
At the moment, we have to choose 1 or the other.

Either duplicate `[page]` or no `/posts/1`.

**Comment by floatingpurr** [comment]
> Thanks for your PR. This approach has one issue. We can't access `/posts/1` anymore. At the moment, we have to choose 1 or the other.
> 
> Either duplicate `[page]` or no `/posts/1`.

Yep, but that is how Astro works. Do we really need `/posts/1`?

**Comment by satnaing** [comment]
@floatingpurr 
Yep, you're right.
We can ignore `posts/1` part.
Plz, can you also update the tag page and resolve the conflicts so that I can merge.

**Comment by floatingpurr** [comment]
It should be fine now.

**Review by satnaing — APPROVED** [review]

**Comment by floatingpurr** [comment]
@satnaing,sorry for fixing conflicts without fixing tags!

**Pull request merged**
